In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

# Load dataset
file_name = 'assignment_data.csv'
data_frame = pd.read_csv(file_name)
data_frame.head(5)

,age,sex,on_art,days_art,temp,gcs,weight,fever,dur_fever,headache,...,platelets,sodium,potassium,csf_lactate,csf_glucose_mg,csf_lymph,csf_amt_removed,viralload,artnaive,Label
0,0.0,0.0,1.0,22.0,NaN,0.0,0.0,1.0,11.0,1.0,...,1.0,139.0,4.080910,4.8,1.0,NaN,10.0,1.432357e+06,1.0,0
1,0.0,1.0,1.0,NaN,35.282291,1.0,1.0,1.0,NaN,1.0,...,1.0,135.0,3.220714,NaN,1.0,NaN,10.0,NaN,0.0,1
2,1.0,0.0,0.0,101.0,NaN,1.0,0.0,0.0,NaN,0.0,...,1.0,134.0,5.261970,NaN,1.0,NaN,16.0,NaN,1.0,1
3,NaN,1.0,0.0,NaN,NaN,1.0,1.0,NaN,14.0,1.0,...,1.0,124.0,3.560370,3.0,1.0,NaN,16.0,NaN,0.0,1
4,NaN,1.0,1.0,49.0,NaN,0.0,0.0,NaN,NaN,1.0,...,1.0,128.0,4.394712,3.8,1.0,NaN,36.0,6.667831e+05,1.0,1

In [2]:
# check the dimensions
data_frame.shape

(2500, 28)

In [3]:
# Check the data types
data_frame.dtypes

age                float64
sex                float64
on_art             float64
days_art           float64
temp               float64
gcs                float64
weight             float64
fever              float64
dur_fever          float64
headache           float64
dur_headache       float64
vischange          float64
dur_vischange      float64
vomit              float64
dur_vomit          float64
cd4                float64
wbc                float64
hemoglobin         float64
platelets          float64
sodium             float64
potassium          float64
csf_lactate        float64
csf_glucose_mg     float64
csf_lymph          float64
csf_amt_removed    float64
viralload          float64
artnaive           float64
Label                int64
dtype: object

In [6]:
# Drop duplicates and fill NaN values with zeor
data_frame.drop_duplicates(data_frame)
data_frame = data_frame.fillna(0)
data_frame.head(5)

,age,sex,on_art,days_art,temp,gcs,weight,fever,dur_fever,headache,...,platelets,sodium,potassium,csf_lactate,csf_glucose_mg,csf_lymph,csf_amt_removed,viralload,artnaive,Label
0,0.0,0.0,1.0,22.0,0.000000,0.0,0.0,1.0,11.0,1.0,...,1.0,139.0,4.080910,4.8,1.0,0.0,10.0,1.432357e+06,1.0,0
1,0.0,1.0,1.0,0.0,35.282291,1.0,1.0,1.0,0.0,1.0,...,1.0,135.0,3.220714,0.0,1.0,0.0,10.0,0.000000e+00,0.0,1
2,1.0,0.0,0.0,101.0,0.000000,1.0,0.0,0.0,0.0,0.0,...,1.0,134.0,5.261970,0.0,1.0,0.0,16.0,0.000000e+00,1.0,1
3,0.0,1.0,0.0,0.0,0.000000,1.0,1.0,0.0,14.0,1.0,...,1.0,124.0,3.560370,3.0,1.0,0.0,16.0,0.000000e+00,0.0,1
4,0.0,1.0,1.0,49.0,0.000000,0.0,0.0,0.0,0.0,1.0,...,1.0,128.0,4.394712,3.8,1.0,0.0,36.0,6.667831e+05,1.0,1

In [5]:
data_frame.describe(include='all')

,age,sex,on_art,days_art,temp,gcs,weight,fever,dur_fever,headache,...,platelets,sodium,potassium,csf_lactate,csf_glucose_mg,csf_lymph,csf_amt_removed,viralload,artnaive,Label
count,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,...,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2500.000000,2.500000e+03,2500.000000,2500.000000
mean,0.197600,0.524000,0.431600,466.630000,16.171210,0.712000,0.616000,0.358000,13.163200,0.902800,...,0.829200,130.610800,2.697440,2.815400,0.998800,44.328800,14.584000,1.702057e+05,0.539200,0.840400
std,0.398268,0.499524,0.495398,838.328478,18.280915,0.452922,0.486455,0.479508,22.190519,0.296289,...,0.376409,7.581657,1.994809,2.604091,0.034627,40.093916,8.838585,4.150306e+05,0.498561,0.366308
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,...,1.000000,127.000000,0.000000,0.000000,1.000000,0.000000,8.000000,0.000000e+00,0.000000,1.000000
50%,0.000000,1.000000,0.000000,10.000000,0.000000,1.000000,1.000000,0.000000,0.000000,1.000000,...,1.000000,130.000000,3.596931,3.100000,1.000000,60.000000,12.000000,0.000000e+00,1.000000,1.000000
75%,0.000000,1.000000,1.000000,577.000000,36.484917,1.000000,1.000000,1.000000,15.250000,1.000000,...,1.000000,135.000000,4.267007,4.600000,1.000000,79.000000,20.000000,1.497864e+05,1.000000,1.000000
max,1.000000,1.000000,1.000000,4199.000000,39.497840,1.000000,1.000000,1.000000,99.000000,1.000000,...,1.000000,148.000000,6.594044,10.100000,1.000000,100.000000,49.000000,2.987758e+06,1.000000,1.000000